
CREATE TABLE CLIENT_EVENT (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    CLIENT_ID UUID NOT NULL,
    OCCURRED_ON TIMESTAMP NOT NULL,
    TYPE VARCHAR(250) NOT NULL,
    EVENT TEXT NOT NULL,
    CONSTRAINT PK_CLIENT_EVENT PRIMARY KEY (ID)
);