
CREATE TABLE CLIENT_EVENT (
    ID VARCHAR(36) NOT NULL DEFAULT (UUID()),
    CLIENT_ID VARCHAR(36) NOT NULL,
    OCCURRED_ON DATETIME NOT NULL,
    TYPE VARCHAR(250) NOT NULL,
    EVENT LONGTEXT NOT NULL,
    CONSTRAINT PK_CLIENT_EVENT PRIMARY KEY (ID)
)