CREATE TABLE ROLE (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_ROLE_NAME UNIQUE (NAME)
);

CREATE TRIGGER ROLE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON ROLE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

CREATE TABLE USER_ROLE (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES "user"(ID),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TRIGGER USER_ROLE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON USER_ROLE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- Create the generic user role
INSERT INTO ROLE (ID, NAME, DESCRIPTION)
VALUES ('0e60c1c0-5934-11eb-9cc6-00cf12e857f9', 'User', 'Default user role.'),
        ('d4a3453f-5935-11eb-9cc6-00cf12e857f9', 'Admin', 'Admin role');

-- Give everyone the user role
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
SELECT 
    u.ID as USER_ID,
   '0e60c1c0-5934-11eb-9cc6-00cf12e857f9' as ROLE_ID
FROM "user" u;
       
