CREATE TABLE ROLE (
    ID VARCHAR(36) NOT NULL DEFAULT UUID(),
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_ROLE_NAME UNIQUE (NAME)
);

CREATE TABLE USER_ROLE (
    ID VARCHAR(36) NOT NULL DEFAULT UUID(),
    USER_ID VARCHAR(36) NOT NULL,
    ROLE_ID VARCHAR(36) NOT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

-- Create the generic user role
INSERT INTO ROLE (ID, NAME, DESCRIPTION)
VALUES ('0e60c1c0-5934-11eb-9cc6-00cf12e857f9', 'User', 'Default user role.'),
        ('d4a3453f-5935-11eb-9cc6-00cf12e857f9', 'Admin', 'Admin role');

-- Give everyone the user role
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
SELECT 
    u.ID as USER_ID,
   '0e60c1c0-5934-11eb-9cc6-00cf12e857f9' as ROLE_ID
FROM USER u;
       
