CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE FUNCTION UPDATE_MODIFIED_DATE_TIMESTAMP()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.MODIFIED_DATE = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';


CREATE TABLE "user" (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TRIGGER USER_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON "user" FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();