CREATE TABLE USER_REGISTRATION_KEY (
    ID VARCHAR(36) NOT NULL DEFAULT (UUID()),
    KEY_VAL VARCHAR(100) NOT NULL UNIQUE,
    USES_REMAINING INT NOT NULL,
    ACTIVE BIT NOT NULL DEFAULT 1,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_REGISTRATION_KEY PRIMARY KEY (ID)
);

CREATE TABLE USER_REGISTRATION_KEY_USE (
    ID VARCHAR(36) NOT NULL DEFAULT (UUID()),
    USER_REGISTRATION_KEY_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_URKU PRIMARY KEY (ID),
    CONSTRAINT FK_URKU_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    CONSTRAINT FK_URKU_URK FOREIGN KEY (USER_REGISTRATION_KEY_ID) REFERENCES USER_REGISTRATION_KEY(ID),
    CONSTRAINT UK_USER_URK UNIQUE (USER_REGISTRATION_KEY_ID, USER_ID)    
);