
CREATE TABLE SCOPE (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SCOPE PRIMARY KEY (ID),
    CONSTRAINT UK_SCOPE_NAME UNIQUE (NAME)
);

CREATE TRIGGER SCOPE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON SCOPE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- A client that can request credentials
CREATE TABLE CLIENT (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    SECRET VARCHAR(2000) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENT PRIMARY KEY (ID)
);

CREATE TRIGGER CLIENT_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON CLIENT FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();


-- Redirect / Post Logout URIs for the client
CREATE TABLE CLIENT_URI (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    CLIENT_ID UUID NOT NULL,
    TYPE INT NOT NULL,
    URI  VARCHAR(5000) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENT_URI PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_URI_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TRIGGER CLIENT_URI_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON CLIENT_URI FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- The scopes the client is allowed to request
CREATE TABLE CLIENT_ALLOWED_SCOPE (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    CLIENT_ID UUID NOT NULL,
    SCOPE_ID UUID NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENT_ALLOWED_SCOPE PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_ALLOWED_SCOPE_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID),
    CONSTRAINT FK_CLIENT_ALLOWED_SCOPE_SCOPE FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(ID)                                  
);

CREATE TRIGGER CLIENT_ALLOWED_SCOPE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON CLIENT_ALLOWED_SCOPE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- The identities a client is allowed, (i.e. what user profile information they can access)
CREATE TABLE CLIENT_ALLOWED_IDENTITY (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    CLIENT_ID UUID NOT NULL,
    IDENTITY INT NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENT_ALLOWED_IDENTITY PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_ALLOWED_IDENTITY_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)    
);

CREATE TRIGGER CLIENT_ALLOWED_IDENTITY_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON CLIENT_ALLOWED_IDENTITY FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- The grant types that a client can use (client creds and/or auth code)
CREATE TABLE CLIENT_ALLOWED_GRANT_TYPE (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    CLIENT_ID UUID NOT NULL,
    GRANT_TYPE INT NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENT_ALLOWED_GRANT_TYPE PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_ALLOWED_GRANT_TYPE_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TRIGGER CLIENT_ALLOWED_GRANT_TYPE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON CLIENT_ALLOWED_GRANT_TYPE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- Defines a Resource / an API
CREATE TABLE RESOURCE(
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    NAME VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_RESOURCE PRIMARY KEY (ID),
    CONSTRAINT UK_RESOURCE_NAME UNIQUE (NAME)
);

CREATE TRIGGER RESOURCE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON RESOURCE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

-- Scopes that the resource allows
CREATE TABLE RESOURCE_SCOPE (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    RESOURCE_ID UUID NOT NULL,
    SCOPE_ID UUID NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_RESOURCE_SCOPE PRIMARY KEY (ID),
    CONSTRAINT FK_RESOURCE_SCOPE_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(ID),
    CONSTRAINT FK_RESOURCE_SCOPE_SCOPE FOREIGN KEY  (SCOPE_ID) REFERENCES  SCOPE(ID)
);

CREATE TRIGGER RESOURCE_SCOPE_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON RESOURCE_SCOPE FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();

