ALTER TABLE  USER
    ADD COLUMN EMAIL_VERIFIED BIT NOT NULL DEFAULT 0;


CREATE TABLE USER_EMAIL_VERIFICATION_REQUEST (
    ID VARCHAR(36) NOT NULL DEFAULT (UUID()),
    USER_ID VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    VALIDATION_KEY VARCHAR(100) NOT NULL,
    SUCCESSFUL BIT NOT NULL DEFAULT 0,
    ACTIVE BIT NOT NULL DEFAULT 0,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_EMAIL_VERIFICATION_REQUEST PRIMARY KEY (ID),
    CONSTRAINT FK_USER_EMAIL_VERIFICATION_REQUEST_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    CONSTRAINT UK_VALIDATION_KEY UNIQUE (VALIDATION_KEY)
);