CREATE TABLE USER (
    ID VARCHAR(36) NOT NULL DEFAULT UUID(),
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    ACTIVE BIT NOT NULL DEFAULT 1,
    LOCKED BIT NOT NULL DEFAULT 0,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);