CREATE TABLE PERSISTED_GRANT (
    ID VARCHAR(200) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    SUBJECT_ID VARCHAR(200) NULL,
    SESSION_ID VARCHAR(200) NULL,
    CLIENT_ID VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(200) NULL,
    CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRATION_DATE DATETIME NULL,
    CONSUMED_DATE DATETIME NULL,
    DATA LONGTEXT NOT NULL,
    CONSTRAINT PK_PERSISTED_GRANT PRIMARY KEY (ID)    
);