ALTER TABLE  "user"
    ADD COLUMN EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE;


CREATE TABLE USER_EMAIL_VERIFICATION_REQUEST (
    ID UUID NOT NULL DEFAULT (uuid_generate_v4()),
    USER_ID UUID NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    VALIDATION_KEY VARCHAR(100) NOT NULL,
    SUCCESSFUL BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_EMAIL_VERIFICATION_REQUEST PRIMARY KEY (ID),
    CONSTRAINT FK_USER_EMAIL_VERIFICATION_REQUEST_USER FOREIGN KEY (USER_ID) REFERENCES "user"(ID),
    CONSTRAINT UK_VALIDATION_KEY UNIQUE (VALIDATION_KEY)
);

CREATE TRIGGER USER_EMAIL_VERIFICATION_REQUEST_UPDATE_MODIFIED_DATE BEFORE UPDATE
    ON USER_EMAIL_VERIFICATION_REQUEST FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_MODIFIED_DATE_TIMESTAMP();